-- DROP TABLE TBL_GRAMMER;
CREATE TABLE TBL_GRAMMER (INPUT_WORD VARCHAR2(3), OUTPUT_WORD VARCHAR2(3));
INSERT INTO TBL_GRAMMER VALUES ('ㅁ', 'A');
INSERT INTO TBL_GRAMMER VALUES ('ㅠ', 'B');
INSERT INTO TBL_GRAMMER VALUES ('ㅊ', 'C');
INSERT INTO TBL_GRAMMER VALUES ('ㅇ', 'D');
INSERT INTO TBL_GRAMMER VALUES ('ㄷ', 'E');
INSERT INTO TBL_GRAMMER VALUES ('ㄹ', 'F');
INSERT INTO TBL_GRAMMER VALUES ('ㅎ', 'G');
INSERT INTO TBL_GRAMMER VALUES ('ㅗ', 'H');
INSERT INTO TBL_GRAMMER VALUES ('ㅑ', 'I');
INSERT INTO TBL_GRAMMER VALUES ('ㅓ', 'J');
INSERT INTO TBL_GRAMMER VALUES ('ㅏ', 'K');
INSERT INTO TBL_GRAMMER VALUES ('ㅣ', 'L');
INSERT INTO TBL_GRAMMER VALUES ('ㅡ', 'M');
INSERT INTO TBL_GRAMMER VALUES ('ㅜ', 'N');
INSERT INTO TBL_GRAMMER VALUES ('ㅐ', 'O');
INSERT INTO TBL_GRAMMER VALUES ('ㅔ', 'P');
INSERT INTO TBL_GRAMMER VALUES ('ㅂ', 'Q');
INSERT INTO TBL_GRAMMER VALUES ('ㄱ', 'R');
INSERT INTO TBL_GRAMMER VALUES ('ㄴ', 'S');
INSERT INTO TBL_GRAMMER VALUES ('ㅅ', 'T');
INSERT INTO TBL_GRAMMER VALUES ('ㅕ', 'U');
INSERT INTO TBL_GRAMMER VALUES ('ㅍ', 'V');
INSERT INTO TBL_GRAMMER VALUES ('ㅈ', 'W');
INSERT INTO TBL_GRAMMER VALUES ('ㅌ', 'X');
INSERT INTO TBL_GRAMMER VALUES ('ㅛ', 'Y');
INSERT INTO TBL_GRAMMER VALUES ('ㅋ', 'Z');
INSERT INTO TBL_GRAMMER VALUES (' ', ' ');
SELECT * FROM TBL_GRAMMER;

-- DROP TABLE TBL_LETTER;
CREATE TABLE TBL_LETTER (NUM NUMBER, INPUT_TEXT VARCHAR2(100), TIME VARCHAR2(17));

-- DROP SEQUENCE SEQ_LETTER;
CREATE SEQUENCE SEQ_LETTER
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

--==============================================================================
-- If you want to show some English words, type in Korean.
-- For example, if you want to show up 'HELLO', then type 'ㅗㄷㅣㅣㅐ'.
SELECT FUNC_GRAMMER('TYPE HERE') AS "CHAT"
  FROM DUAL;
--==============================================================================    