CREATE OR REPLACE FUNCTION DUPLICATE_CHECK
(
    vID         TBL_PRTC_BEFORE.ID%TYPE
)
RETURN TBL_PRTC_AFTER.ID%TYPE
IS
    vIS_EXIST   TBL_PRTC_AFTER.ID%TYPE;
BEGIN
    SELECT ID
      INTO vIS_EXIST
      FROM TBL_PRTC_AFTER
     WHERE ID = LPAD(vID, 4, '0');
     
    RETURN vIS_EXIST;
END;
/