SELECT * FROM TBL_PRTC_BEFORE;
SELECT * FROM TBL_PRTC_AFTER ORDER BY 1;
SELECT * FROM TBL_PRTC_LOG ORDER BY 1;

EXEC RUN_JOB;

INSERT INTO TBL_PRTC_BEFORE VALUES('11', 'Clementina TEST', 'TEST.TEST', 'TEST.TEST@TEST.COM', '024-648-3804', 'TEST', SYSDATE);